languaje: node_js
node_js:
    - 13
    
service:
    - docker
    
install:
    - echo "nothing to be installed"
    
before_script:
    - echo "no test"
    
script:
    - docker --version
    - docker build -t simple-node .
    - docker tag simple-node jmespartero/simple-node:latest

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push jmespartero/simple-node